name: Release

on:
  push:
    tags:
      - 'v1.0.1' # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2' # Matches your recommended version
          
      - name: Get tag version
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Make release directory
        run: mkdir -p release
        
      - name: Run release script (adapted)
        run: |
          # Make the script executable
          chmod +x ./release.sh
          
          # Execute with the detected version
          ./release.sh ${{ env.VERSION }}
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: |
            ## GHAM ${{ env.VERSION }}
            
            ### Installation
            
            #### Download binaries
            Download the appropriate binary for your system from the assets below.
            
            #### Via Go
            ```bash
            go install github.com/riad804/gham@${{ env.VERSION }}
            ```
          files: |
            release/${{ env.VERSION }}/gham-*
          draft: false
          prerelease: ${{ contains(env.VERSION, '-') }}